# Generated by Django 4.2 on 2025-10-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('lecturer_name', models.CharField(max_length=100)),
                ('faculty_name', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=100)),
                ('lesson_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical')], max_length=10)),
            ],
        ),
    ]
